# Generated by Django 5.0 on 2024-05-13 16:13

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Название")),
                ("content", ckeditor.fields.RichTextField(verbose_name="Текст")),
                (
                    "translated_content",
                    ckeditor.fields.RichTextField(verbose_name="Перевод"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_text",
                    models.CharField(max_length=255, verbose_name="Текст вопроса"),
                ),
                ("answer", models.TextField(verbose_name="Ответ")),
                (
                    "choice_a",
                    models.CharField(max_length=200, verbose_name="Вариант A"),
                ),
                (
                    "choice_b",
                    models.CharField(max_length=200, verbose_name="Вариант B"),
                ),
                (
                    "choice_c",
                    models.CharField(max_length=200, verbose_name="Вариант C"),
                ),
                (
                    "choice_d",
                    models.CharField(max_length=200, verbose_name="Вариант D"),
                ),
                (
                    "correct_answer",
                    models.CharField(max_length=1, verbose_name="Правильный ответ"),
                ),
                (
                    "tale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="tales.tale",
                        verbose_name="Сказка",
                    ),
                ),
            ],
        ),
    ]
